### ISSUE TITLE
ModuleNotFoundError: No module named 'OMIEData.Enums'; 'OMIEData' is not a package

### ISSUE THREAD

**Issue by cibernicola** [acruzgarcia/OMIEData#1]
That's the message I'm seeing after a pip installation and trying "example_energy_by_technology_2steps.py" example.

```
Traceback (most recent call last):
  File "****/OMIEData.py", line 4, in <module>
    from OMIEData.DataImport.omie_data_importer_from_folder import OMIEDataImporterFromFolder
  File "****\OMIEData.py", line 4, in <module>
    from OMIEData.DataImport.omie_data_importer_from_folder import OMIEDataImporterFromFolder
ModuleNotFoundError: No module named 'OMIEData.DataImport'; 'OMIEData' is not a package
```

¿Is it working?

(Python 3.6 Windows 10)

**Comment by acruzgarcia** [comment]
Hi cibernicola,

That does not seem to be working. I do not think you installed the package properly.  

Please follow installation instruction as in 
https://github.com/acruzgarcia/OMIEData
Installation section.

Let me know how it goes.

**Comment by cibernicola** [comment]
Now it works correctly, although I have not done anything on my part :)
Thank you!

**Comment by acruzgarcia** [comment]
Glad to hear that it works fine :)
